#!/bin/bash
# Menu

user=root
password=benja101829

eval

PS3='Please enter your choice: '
options=("Create user" "Modify user" "Delete user" "Stablish password" "Create group" "Delete group" "Quit")
select opt in "${options[@]}"
do
	case $opt in
		"Create user")
			if [ $(id -u) -eq 0 ]; then
				read -p "Enter username : " username
				read -s -p "Enter password : " password
				egrep "^$username" /etc/passwd >/dev/null
				if [ $? -eq 0 ]; then
					echo "$username exists!"
					exit 1
				else
					pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
					useradd -m -p $pass $username
					[ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
				fi
			else
				echo "Only root may add a user to the system"
				exit 2
			fi
			;;
		"Modify user")
			echo "you chose choice 2"
			;;
		"Delete user")
			echo "you chose choice 3"
			;;
		"Stablish password")

			;;
		"Create group")

			;;
		"Delete group")

			;;


		"Quit")
			break
			;;
		*) 
			echo invalid option;;
	esac
done	