#!/bin/bash
# Menu

user=root
password=benja101829

eval

PS3='Please enter your choice: '
options=("Create user" "Modify user" "Delete user" "Stablish password" "Create group" "Delete group" "Quit")
select opt in "${options[@]}"
do
	case $opt in
		"Create user")

				read -p "Enter username : " username
				eval sudo adduser $username
			
			;;
		"Modify user")
				read -p "Enter username : " username
				eval sudo usermod $username
				echo "The user was modify"
			;;
		"Delete user")
				read -p "Enter username : " username
				eval sudo userdel $username
				echo "The user was delete"
			;;
		"Stablish password")
				groupadd newgroup
				read -p "Enter username : " username
				eval sudo userdel $username
				echo "The user was delete"
			;;
		"Create group")

			;;
		"Delete group")

			;;


		"Quit")
			break
			;;
		*) 
			echo invalid option;;
	esac
done	