#!/bin/bash
# Menu

user=root
password=benja101829

eval

PS3='Please enter your choice: '
options=("Create user" "Modify user" "Delete user" "Stablish password" "Create group" "Delete group" "Quit")
select opt in "${options[@]}"
do
	case $opt in
		"Create user")
			echo "pase..........."

				read -p "Enter username : " username
				read -s -p "Enter password : " password

				eval sudo adduser $username
				echo $password
			;;
		"Modify user")
			echo "you chose choice 2"
			;;
		"Delete user")
			echo "you chose choice 3"
			;;
		"Stablish password")

			;;
		"Create group")

			;;
		"Delete group")

			;;


		"Quit")
			break
			;;
		*) 
			echo invalid option;;
	esac
done	